version: '3.8'

services:
  notice-screen:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5009:5009"
    container_name: notice-screen
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - REDIRECT_URL=https://www.google.com
      - ACKNOWLEDGMENT_TIMEOUT_DAYS=14
      - STATUS_PAGE=https://www.google.com
    command: flask run --host=0.0.0.0 --port=5009 